services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "container:gluetun"
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Dublin
    # ports:
    #   - 8191:8191
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 512m
    restart: unless-stopped
