version: "3.7"
services:
  deluge:
    network_mode: "container:gluetun"
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - DELUGE_LOGLEVEL=info # optional
    volumes:
      - ${HOME}/Documents/docker/data/deluge/config:/config
      - ${HOME}/Documents/docker/shared/downloads:/downloads
    # ports:
    #   - 8112:8112
    restart: unless-stopped
