version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    network_mode: "container:gluetun"
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - AUTO_UPDATE=false #optional — Watchtower handles updates
    volumes:
      - ${HOME}/Documents/docker/data/jackett/config:/config
      - ${HOME}/Documents/docker/shared/downloads:/downloads
    # ports:
    #   - 9117:9117
    restart: unless-stopped
