services:
  caddy:
    image: slothcroissant/caddy-cloudflaredns:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_DATA_HOME}/caddy_data:/data
      - ${DOCKER_DATA_HOME}/caddy_config:/config
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - proxy_net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    mem_limit: 256m
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}

configs:
  caddyfile:
    content: |
      {
          acme_dns cloudflare {env.CLOUDFLARE_API_TOKEN}
      }

      portainer.longie.net {
          reverse_proxy 192.168.1.6:9443 {
              transport http {
                  tls_insecure_skip_verify
              }
          }
          header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains"
              X-Frame-Options "SAMEORIGIN"
              X-Content-Type-Options "nosniff"
          }
      }

      sonarr.longie.net {
          reverse_proxy 192.168.1.6:8989
          header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains"
              X-Frame-Options "SAMEORIGIN"
              X-Content-Type-Options "nosniff"
          }
      }

      jackett.longie.net {
          reverse_proxy 192.168.1.6:9117
          header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains"
              X-Frame-Options "SAMEORIGIN"
              X-Content-Type-Options "nosniff"
          }
      }

      qbt.longie.net {
          reverse_proxy 192.168.1.6:8080
          header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains"
              X-Frame-Options "SAMEORIGIN"
              X-Content-Type-Options "nosniff"
          }
      }

networks:
  proxy_net:
    name: proxy_net
    driver: bridge
