services:
  portainer:
    image: portainer/portainer-ce:2.27.3
    container_name: portainer
    restart: unless-stopped
    ports:
      - 127.0.0.1:9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DATA_HOME}/portainer:/data
    command: --trusted-origins https://portainer.longie.net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 512m
